# Generated by Django 5.0.1 on 2024-10-25 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_names', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('variables', models.ManyToManyField(to='app.variable')),
            ],
        ),
        migrations.CreateModel(
            name='VariableWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=3, max_digits=5)),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.formula')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.variable')),
            ],
            options={
                'unique_together': {('variable', 'formula')},
            },
        ),
    ]
